# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pendant App.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 822)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.servo1_slider = QtWidgets.QSlider(self.centralwidget)
        self.servo1_slider.setGeometry(QtCore.QRect(140, 170, 261, 51))
        self.servo1_slider.setMouseTracking(False)
        self.servo1_slider.setAutoFillBackground(False)
        self.servo1_slider.setMaximum(180)
        self.servo1_slider.setProperty("value", 93)
        self.servo1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo1_slider.setObjectName("servo1_slider")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(310, 20, 491, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE.setFont(font)
        self.TITLE.setObjectName("TITLE")
        self.servo2_slider = QtWidgets.QSlider(self.centralwidget)
        self.servo2_slider.setGeometry(QtCore.QRect(140, 240, 261, 51))
        self.servo2_slider.setMaximum(180)
        self.servo2_slider.setProperty("value", 93)
        self.servo2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo2_slider.setObjectName("servo2_slider")
        self.servo3_slider = QtWidgets.QSlider(self.centralwidget)
        self.servo3_slider.setGeometry(QtCore.QRect(140, 310, 261, 51))
        self.servo3_slider.setMaximum(180)
        self.servo3_slider.setProperty("value", 93)
        self.servo3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo3_slider.setObjectName("servo3_slider")
        self.servo4_slider = QtWidgets.QSlider(self.centralwidget)
        self.servo4_slider.setGeometry(QtCore.QRect(140, 380, 261, 51))
        self.servo4_slider.setMaximum(180)
        self.servo4_slider.setProperty("value", 93)
        self.servo4_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo4_slider.setObjectName("servo4_slider")
        self.servo5_slider = QtWidgets.QSlider(self.centralwidget)
        self.servo5_slider.setGeometry(QtCore.QRect(140, 450, 261, 51))
        self.servo5_slider.setMaximum(180)
        self.servo5_slider.setProperty("value", 93)
        self.servo5_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo5_slider.setObjectName("servo5_slider")
        self.servo6_slider = QtWidgets.QSlider(self.centralwidget)
        self.servo6_slider.setGeometry(QtCore.QRect(140, 520, 261, 51))
        self.servo6_slider.setMaximum(180)
        self.servo6_slider.setProperty("value", 93)
        self.servo6_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo6_slider.setObjectName("servo6_slider")
        self.label_s1 = QtWidgets.QLabel(self.centralwidget)
        self.label_s1.setEnabled(True)
        self.label_s1.setGeometry(QtCore.QRect(30, 170, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_s1.setFont(font)
        self.label_s1.setTextFormat(QtCore.Qt.AutoText)
        self.label_s1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s1.setObjectName("label_s1")
        self.label_s2 = QtWidgets.QLabel(self.centralwidget)
        self.label_s2.setGeometry(QtCore.QRect(30, 240, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_s2.setFont(font)
        self.label_s2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s2.setObjectName("label_s2")
        self.label_s3 = QtWidgets.QLabel(self.centralwidget)
        self.label_s3.setGeometry(QtCore.QRect(30, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_s3.setFont(font)
        self.label_s3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s3.setObjectName("label_s3")
        self.label_s4 = QtWidgets.QLabel(self.centralwidget)
        self.label_s4.setGeometry(QtCore.QRect(30, 380, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_s4.setFont(font)
        self.label_s4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s4.setObjectName("label_s4")
        self.label_s5 = QtWidgets.QLabel(self.centralwidget)
        self.label_s5.setGeometry(QtCore.QRect(30, 450, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_s5.setFont(font)
        self.label_s5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s5.setObjectName("label_s5")
        self.label_s6 = QtWidgets.QLabel(self.centralwidget)
        self.label_s6.setGeometry(QtCore.QRect(30, 520, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_s6.setFont(font)
        self.label_s6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s6.setObjectName("label_s6")
        self.verticalSlider_Speed = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_Speed.setGeometry(QtCore.QRect(640, 209, 41, 311))
        self.verticalSlider_Speed.setMinimum(5)
        self.verticalSlider_Speed.setMaximum(100)
        self.verticalSlider_Speed.setProperty("value", 20)
        self.verticalSlider_Speed.setSliderPosition(20)
        self.verticalSlider_Speed.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_Speed.setObjectName("verticalSlider_Speed")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 150, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(440, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(440, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(440, 390, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(440, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_Speed = QtWidgets.QLabel(self.centralwidget)
        self.label_Speed.setGeometry(QtCore.QRect(600, 530, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Speed.setFont(font)
        self.label_Speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Speed.setObjectName("label_Speed")
        self.pushButton_sendData = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sendData.setGeometry(QtCore.QRect(50, 610, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sendData.setFont(font)
        self.pushButton_sendData.setObjectName("pushButton_sendData")
        self.pushButton_Save_Single = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save_Single.setGeometry(QtCore.QRect(370, 610, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save_Single.setFont(font)
        self.pushButton_Save_Single.setObjectName("pushButton_Save_Single")
        self.pushButton_StartProg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartProg.setGeometry(QtCore.QRect(210, 610, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_StartProg.setFont(font)
        self.pushButton_StartProg.setObjectName("pushButton_StartProg")
        self.pushButton_data1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_data1.setGeometry(QtCore.QRect(880, 440, 141, 41))
        self.pushButton_data1.setObjectName("pushButton_data1")
        self.pushButton_data2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_data2.setGeometry(QtCore.QRect(880, 490, 141, 41))
        self.pushButton_data2.setObjectName("pushButton_data2")
        self.pushButton_data3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_data3.setGeometry(QtCore.QRect(880, 540, 141, 41))
        self.pushButton_data3.setObjectName("pushButton_data3")
        self.pushButton_data4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_data4.setGeometry(QtCore.QRect(880, 590, 141, 41))
        self.pushButton_data4.setObjectName("pushButton_data4")
        self.pushButton_data5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_data5.setGeometry(QtCore.QRect(880, 640, 141, 41))
        self.pushButton_data5.setObjectName("pushButton_data5")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(820, 700, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(820, 150, 231, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 186, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_port = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_port.setFont(font)
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_baud = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_baud.sizePolicy().hasHeightForWidth())
        self.comboBox_baud.setSizePolicy(sizePolicy)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_baud)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_searchPorts = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_searchPorts.setObjectName("pushButton_searchPorts")
        self.verticalLayout.addWidget(self.pushButton_searchPorts)
        self.pushButton_openPort = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_openPort.setObjectName("pushButton_openPort")
        self.verticalLayout.addWidget(self.pushButton_openPort)
        self.pushButton_closePort = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_closePort.setObjectName("pushButton_closePort")
        self.verticalLayout.addWidget(self.pushButton_closePort)
        self.label_portStatus = QtWidgets.QLabel(self.frame)
        self.label_portStatus.setGeometry(QtCore.QRect(10, 240, 191, 20))
        self.label_portStatus.setText("")
        self.label_portStatus.setObjectName("label_portStatus")
        self.pushButton_Save_All = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save_All.setGeometry(QtCore.QRect(530, 610, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save_All.setFont(font)
        self.pushButton_Save_All.setObjectName("pushButton_Save_All")
        self.textBrowser_points = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_points.setGeometry(QtCore.QRect(60, 670, 256, 91))
        self.textBrowser_points.setObjectName("textBrowser_points")
        self.textBrowser_points_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_points_2.setGeometry(QtCore.QRect(410, 670, 256, 91))
        self.textBrowser_points_2.setObjectName("textBrowser_points_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuButton_UserManuel = QtWidgets.QAction(MainWindow)
        self.menuButton_UserManuel.setObjectName("menuButton_UserManuel")
        self.menuMenu.addAction(self.menuButton_UserManuel)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TITLE.setText(_translate("MainWindow", "Pendant App v0.1 (Alpha) ©"))
        self.label_s1.setText(_translate("MainWindow", "93"))
        self.label_s2.setText(_translate("MainWindow", "93"))
        self.label_s3.setText(_translate("MainWindow", "93"))
        self.label_s4.setText(_translate("MainWindow", "93"))
        self.label_s5.setText(_translate("MainWindow", "93"))
        self.label_s6.setText(_translate("MainWindow", "93"))
        self.label.setText(_translate("MainWindow", "Speed (Delay as MS)"))
        self.label_7.setText(_translate("MainWindow", "Base"))
        self.label_8.setText(_translate("MainWindow", "Arm 1"))
        self.label_9.setText(_translate("MainWindow", "Arm 2"))
        self.label_10.setText(_translate("MainWindow", "Roll"))
        self.label_11.setText(_translate("MainWindow", "Pitch"))
        self.label_12.setText(_translate("MainWindow", "Gripper"))
        self.label_Speed.setText(_translate("MainWindow", "20"))
        self.pushButton_sendData.setText(_translate("MainWindow", "MOVE"))
        self.pushButton_Save_Single.setText(_translate("MainWindow", "SAVE POINT"))
        self.pushButton_StartProg.setText(_translate("MainWindow", "START"))
        self.pushButton_data1.setText(_translate("MainWindow", "DATA 1"))
        self.pushButton_data2.setText(_translate("MainWindow", "DATA 2"))
        self.pushButton_data3.setText(_translate("MainWindow", "DATA 3"))
        self.pushButton_data4.setText(_translate("MainWindow", "DATA 4"))
        self.pushButton_data5.setText(_translate("MainWindow", "DATA 5"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))
        self.label_3.setText(_translate("MainWindow", "SETTINGS"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.label_4.setText(_translate("MainWindow", "Baud Rate"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "1800"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(4, _translate("MainWindow", "19200"))
        self.comboBox_baud.setItemText(5, _translate("MainWindow", "115200"))
        self.pushButton_searchPorts.setText(_translate("MainWindow", "Search Ports"))
        self.pushButton_openPort.setText(_translate("MainWindow", "Connect"))
        self.pushButton_closePort.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_Save_All.setText(_translate("MainWindow", "SAVE WORK"))
        self.textBrowser_points.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_points_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuButton_UserManuel.setText(_translate("MainWindow", "User Manuel"))

